accounts/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from jobsapp.views import EditProfileView
from .views import *

app_name = "accounts"

urlpatterns = [
    path('employee/register', RegisterEmployeeView.as_view(), name='employee-register'),
    path('employer/register', RegisterEmployerView.as_view(), name='employer-register'),
    path('employee/profile/update', EditProfileView.as_view(), name='employer-profile-update'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('login', LoginView.as_view(), name='login'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
]

jobsapp/urls.py
from django.urls import path, include

from .views import *

app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),
    path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    path('profile', ProfileView.as_view(), name='employer-profile'),
    path('employee/profile', ApplicantProfileView.as_view(), name='employee-profile'),
]

jobsapp/views/home.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView

from jobsapp.forms import ApplyJobForm
from jobsapp.models import Job, Applicant


class HomeView(ListView):
    model = Job
    template_name = 'home.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.all()[:6]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['trendings'] = self.model.objects.filter(created_at__month=timezone.now().month)[:3]
        return context


class SearchView(ListView):
    model = Job
    template_name = 'jobs/search.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        return self.model.objects.filter(location__contains=self.request.GET['location'],
                                         title__contains=self.request.GET['position'])


class JobListView(ListView):
    model = Job
    template_name = 'jobs/jobs.html'
    context_object_name = 'jobs'
    paginate_by = 5


class JobDetailsView(DetailView):
    model = Job
    template_name = 'jobs/details.html'
    context_object_name = 'job'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(JobDetailsView, self).get_object(queryset=queryset)
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            # redirect here
            raise Http404("Job doesn't exists")
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)


class ApplyJobView(CreateView):
    model = Applicant
    form_class = ApplyJobForm
    slug_field = 'job_id'
    slug_url_kwarg = 'job_id'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            messages.info(self.request, 'Successfully applied for the job!')
            return self.form_valid(form)
        else:
            return HttpResponseRedirect(reverse_lazy('jobs:home'))

    def get_success_url(self):
        return reverse_lazy('jobs:jobs-detail', kwargs={'id': self.kwargs['job_id']})

    # def get_form_kwargs(self):
    #     kwargs = super(ApplyJobView, self).get_form_kwargs()
    #     print(kwargs)
    #     kwargs['job'] = 1
    #     return kwargs

    def form_valid(self, form):
        # check if user already applied
        applicant = Applicant.objects.filter(user_id=self.request.user.id, job_id=self.kwargs['job_id'])
        if applicant:
            messages.info(self.request, 'You already applied for this job')
            return HttpResponseRedirect(self.get_success_url())
        # save applicant
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %} {% endblock %} - AceTech</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/logo/Acetech.png' %}">

		<!-- CSS here -->
        <link type="text/css" href="{% static 'assets/css/pixel.css' %}" rel="stylesheet">
            <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/price_rangs.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
            <link rel="stylesheet" href="{% static 'assets/scss/style.scss' %}">
   </head>

   <body>

    <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <a href="/"><img src="{% static 'assets/img/logo/Acetech.png' %}" alt=""></a>
                            </div>  
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="/">Home</a></li>
                                            <li><a href="{% url 'jobs:jobs' %}">Find a Job </a></li>
                                            <li><a href="">About</a></li>
                                            <li><a href="">Contact</a></li>
                                            
                                            {% if request.user.is_authenticated and request.user.role == 'employer' %}
                                                <li><a href="{% url 'jobs:employer-profile' %}" style="color:#fb246a">
                                                    {% if request.user.role == 'employee' %}
                                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                                {% else %}
                                                    {{ request.user.first_name }}
                                                {% endif %}</a>
                                                    <ul class="submenu">
                                                        <li><a href="{% url 'jobs:employer-dashboard' %}">Dashboard</a></li>
                                                        <li><a href="{% url 'jobs:employer-all-applicants' %}">Applicants</a></li>
                                                        <li><a href="{% url 'jobs:employer-jobs-create' %}">Post a Job</a></li>
                                                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                                                    </ul>
                                                </li>
                                            {% elif request.user.is_authenticated and request.user.role == 'employee' %} 
                                                <li><a href="{% url 'jobs:employee-profile' %}"style="color:#fb246a">{% if request.user.role == 'employee' %}
                                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                                {% else %}
                                                    {{ request.user.first_name }}
                                                {% endif %}</a>
                                                    <ul class="submenu">
                                                        <li><a href="{% url 'accounts:employer-profile-update' %}">Edit Profile</a></li>
                                                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                                                    </ul>
                                                </li>
                                            {% else %}
                                            <li><a href="#">Register</a>
                                                <ul class="submenu">
                                                    
                                                    <li><a href="{% url 'accounts:employee-register' %}">As Employee</a></li>
                                                    <li><a href="{% url 'accounts:employer-register' %}">As Employer</a></li>
                                                    
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'accounts:login' %}" >Login</a></li>
                                        </ul>
                                    </nav>
                                </div>          
                               
                                {% endif %}
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>


    
{% block content %}

{% endblock content %}
<div class="footer-bottom-area footer-bg">
    <div class="container">
        <div class="footer-border">
             <div class="row d-flex justify-content-between align-items-center">
                 <div class="col-xl-10 col-lg-10 ">
                     <div class="footer-copy-right">
                         <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | By <a href="">AceTech </a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                     </div>
<script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static './assets/js/popper.min.js' %}"></script>
        <script src="{% static './assets/js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
        <script src="{% static './assets/js/slick.min.js' %}"></script>
        <script src="{% static './assets/js/price_rangs.js' %}"></script>
        
		<!-- One Page, Animated-HeadLin -->
        <script src="./assets/js/wow.min.js"></script>
		<script src="./assets/js/animated.headline.js"></script>
        <script src="./assets/js/jquery.magnific-popup.js"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="./assets/js/jquery.scrollUp.min.js"></script>
        <script src="./assets/js/jquery.nice-select.min.js"></script>
		<script src="./assets/js/jquery.sticky.js"></script>
        
        <!-- contact js -->
        <script src="./assets/js/contact.js"></script>
        <script src="./assets/js/jquery.form.js"></script>
        <script src="./assets/js/jquery.validate.min.js"></script>
        <script src="{% static './assets/js/mail-script.js' %}"></script>
        <script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static './assets/js/plugins.js' %}"></script>
        <script src="{% static './assets/js/main.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    Home
{% endblock %}

{% block content %}

<main>
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="slider-active" style="background-color: #8BC6EC;
        background-image: linear-gradient(135deg, #eeaeca 0%, #94bbe9 100%);
        ">
            <div class="single-slider slider-height d-flex align-items-center bg-img-1">
                <div class="container" >
                    <div class="row">
                        <div class="col-xl-6 col-lg-9 col-md-10">
                            <div class="hero__caption">
                                <h1>Find the most exciting startup jobs</h1>
                            </div>
                        </div>
                    </div>
                    <!-- Search Box -->
                    <div class="row">
                        <div class="col-xl-8">
                            <!-- form -->
                            <form id="job-main-form" method="get" action="{% url 'jobs:searh' %}" class="job-main-form">
                                <div class="controls" style="color: black;">
                                    <div class="row align-items-center">
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label for="profession">Position</label>
                                                <input type="text" id="profession" name="position"
                                                       placeholder="Position you are looking for" class="form-control" style="color: black">
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label for="location">Location</label>
                                                <input type="text" id="location" name="location"
                                                       placeholder="Any particular location?" class="form-control">
                                            </div>
                                        </div>
                                        <div class="col-md-2" >
                                            <button type="submit"
                                                    class="btn job-main-form__button">
                                                Search
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->
    <section class="featured-job-area feature-padding">
        <div class="container">
            <!-- Section Tittle -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-tittle text-center">
                        <span>Recent Job</span>
                        <h2>Featured Jobs</h2>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-10">
                    {% for job in jobs %}
                    <!-- single-job-content -->
                    <div class="single-job-items mb-30">
                        <div class="job-items">
                            <div class="job-tittle">
                                <a href="{% url 'jobs:jobs-detail' job.id %}"><h4>{{ job.title }}</h4></a>
                                <ul>
                                    <li>{{ job.company_name }}</li>
                                    <li><i class="fas fa-map-marker-alt"></i>{{ job.location }}</li>
                                    <li> Rs. {{ job.salary }}</li>
                                </ul>
                            </div>
                        </div>
                        <div class="items-link f-right">
                            {% if job.type == '1' %}
                            <a href="">Full Time</a>
                                    {% elif job.type == '2' %}
                                    <a href="">Part Time</a>
                                    {% else %}
                                    <a href="">Internship</a>

                                    {% endif %}
                                    {% if job.filled %}
                                    <span><b>FullFilled</b></span>
                                    {% else %}
                            <span>{{ job.last_date }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <!-- single-job-content -->
                    {% endfor %}
                    
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="browse-btn2 text-center mt-50">
                            <a href="{% url 'jobs:jobs' %}" class="border-btn2">Browse All Jobs</a>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        
    </section>

    <!-- Our Services Start -->
    <div class="our-services section-pad-t10 pt-150 pb-150 " style="background:#F2F2F2">
        <div class="container">
            <!-- Section Tittle -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-tittle text-center">
                        <span>FEATURED TOURS Packages</span>
                        <h2>Browse Top Categories </h2>
                    </div>
                </div>
            </div>
        
            <div class="row d-flex justify-contnet-center">
                {% for job in jobs %}
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                    <div class="single-services text-center mb-30">
                        <div class="services-ion">
                            <span class="flaticon-tour"></span>
                        </div>
                        <div class="services-cap">
                           <h5><a href="">{{job.category}}</a></h5>
                            <span>(6)</span>
                        </div>
                    </div>
                </div>{% endfor %}
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="browse-btn2 text-center mt-50">
                        <a href="{% url 'jobs:jobs' %}" class="border-btn2">Browse All Sectors</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="apply-process-area apply-bg pt-150 pb-150" style="background:#1f2b7b" >
        <div class="container">
            <!-- Section Tittle -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-tittle white-text text-center">
                        <span>Apply process</span>
                        <h2> How it works</h2>
                    </div>
                </div>
            </div>
            <!-- Apply Process Caption -->
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="single-process text-center mb-30">
                        <div class="process-ion">
                            <span class="flaticon-search"></span>
                        </div>
                        <div class="process-cap">
                           <h5>1. Search a job</h5>
                           <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single-process text-center mb-30">
                        <div class="process-ion">
                            <span class="flaticon-curriculum-vitae"></span>
                        </div>
                        <div class="process-cap">
                           <h5>2. Apply for job</h5>
                           <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single-process text-center mb-30">
                        <div class="process-ion">
                            <span class="flaticon-tour"></span>
                        </div>
                        <div class="process-cap">
                           <h5>3. Get your job</h5>
                           <p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod tempor incididunt ut laborea.</p>
                        </div>
                    </div>
                </div>
            </div>
         </div>
    </div>


</main>

{% endblock %} 